server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    charset utf-8;

    error_log /dev/stdout info;
    access_log /dev/stdout;

    location /.git { deny all; return 403; }

    # Site estático multipágina: / , /pre/ , /vsl/ , /back/
    location / {
        try_files $uri $uri/ =404;
    }
}
