server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;
    absolute_redirect off;
    port_in_redirect off;

    # Presell na raiz para TODOS (200-OK universal). O filtro vive no player vTurb.
    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
}
